### ISSUE TITLE
Overview of clustering algorithms

### ISSUE THREAD

**Issue by eriknovak** [E3-JSI/dataset-OG2021#3]
This task provides an overview of the different clustering algorithms that can be used to cluster the news articles.

The clustering algorithms and approaches should take into consideration that:
- we do not know the final number of clusters
- the number of news articles is huge
- it should provide quality clusters, i.e. articles that talk about the same event should be assigned to the same cluster

Take into consideration that it is OK if there are multiple clusters that are about the same event. Our goal is to avoid having clusters with articles covering multiple events.

**Comment by austirol** [comment]
We propose to use HDBSCAN because it does not require the number of clusters and recognizes outliers. We chose HDBSCAN for its efficiency over DBSCAN and OPTICS.
